# action.yml
name: 'CI CD to Deploy Files and Restart Services'
description: 'Deploy file to your server use sftp & ssh private key'

branding:
  icon: arrow-right-circle
  color: blue

inputs:
  username:
    description: 'username'
    required: true
  server:  
    description: 'Your SFTP server, example, IP Address or ssh.example.com or sftp.example.com'
    required: true
  port: 
    description: 'Your SFTP server port, defaults to 22'
    required: true
    default: "22"
  ssh_private_key:
    description: 'you can copy private_key from your *.pem file, keep format'
    required: true
  local_path:
    description: 'Source Path used for Copying the Files From'
    required: true
    default: ./*
  remote_path:
    description: 'Detination Path used for Deploying the Files To'
    required: true
  sftp_only:
    description: 'Connection will be using the sftp protocol only'
    required: false
    default: false
  sftpArgs:
    description: 'sftp args'
    required: false
  delete_remote_files:
    description: 'This operation will delete all files in the remote path before uploading the files. In case, you don't want to touch the existing files, then leave this as blank. Defaults to false'
    required: false
    default: false
  password:
    description: "SSH passsword. In case, a password is set, the SSH key pair will be ignored"
    required: false
  service_commands:
    description: "Service Command for Starting, Stopping, or, Restarting Services. To be executed on the Remote Server"
    default: ""
    required: false


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.server }}
    - ${{ inputs.port }}
    - ${{ inputs.ssh_private_key }}
    - ${{ inputs.local_path }}
    - ${{ inputs.remote_path }}
    - ${{ inputs.sftp_only }}
    - ${{ inputs.sftpArgs }}
    - ${{ inputs.delete_remote_files }}
    - ${{ inputs.password }}
    - ${{ inputs.service_command }}
